const WORDS_1KYU = [
  { word: "abate", pos: "動詞", meaning: "和らぐ、弱まる", example: "The storm finally began to abate.", exampleJa: "嵐がようやく弱まり始めた。" },
  { word: "aberration", pos: "名詞", meaning: "異常、逸脱", example: "His rude behavior was an aberration.", exampleJa: "彼の無礼な振る舞いは異常だった。" },
  { word: "abhor", pos: "動詞", meaning: "忌み嫌う", example: "I abhor all forms of violence.", exampleJa: "私はあらゆる暴力を忌み嫌う。" },
  { word: "acrimonious", pos: "形容詞", meaning: "辛辣な、とげとげしい", example: "The debate became acrimonious.", exampleJa: "議論はとげとげしくなった。" },
  { word: "admonish", pos: "動詞", meaning: "叱る、戒める", example: "The teacher admonished the student for being late.", exampleJa: "先生は生徒が遅刻したことを叱った。" },
  { word: "adroit", pos: "形容詞", meaning: "巧みな、器用な", example: "She is adroit at handling difficult clients.", exampleJa: "彼女は難しい顧客への対応が巧みだ。" },
  { word: "affable", pos: "形容詞", meaning: "愛想の良い", example: "He greeted us with an affable smile.", exampleJa: "彼は愛想の良い笑顔で私たちを迎えた。" },
  { word: "aloof", pos: "形容詞", meaning: "よそよそしい、打ち解けない", example: "She remained aloof from her colleagues.", exampleJa: "彼女は同僚たちと打ち解けなかった。" },
  { word: "ambiguous", pos: "形容詞", meaning: "曖昧な", example: "His answer was deliberately ambiguous.", exampleJa: "彼の答えは意図的に曖昧だった。" },
  { word: "ameliorate", pos: "動詞", meaning: "改善する", example: "The new policy will ameliorate working conditions.", exampleJa: "新しい方針は労働環境を改善するだろう。" },
  { word: "amenable", pos: "形容詞", meaning: "従順な、応じる", example: "He is amenable to any reasonable suggestion.", exampleJa: "彼は合理的な提案であれば何にでも応じる。" },
  { word: "antipathy", pos: "名詞", meaning: "反感、嫌悪", example: "There was mutual antipathy between them.", exampleJa: "彼らの間には互いに反感があった。" },
  { word: "apathy", pos: "名詞", meaning: "無関心", example: "Voter apathy is a serious problem.", exampleJa: "有権者の無関心は深刻な問題だ。" },
  { word: "arduous", pos: "形容詞", meaning: "骨の折れる、困難な", example: "Climbing the mountain was an arduous task.", exampleJa: "山を登ることは骨の折れる仕事だった。" },
  { word: "assiduous", pos: "形容詞", meaning: "勤勉な、熱心な", example: "She was assiduous in her studies.", exampleJa: "彼女は勉強に熱心だった。" },
  { word: "astute", pos: "形容詞", meaning: "抜け目のない、鋭敏な", example: "He is an astute businessman.", exampleJa: "彼は抜け目のない実業家だ。" },
  { word: "audacious", pos: "形容詞", meaning: "大胆不敵な", example: "It was an audacious plan.", exampleJa: "それは大胆不敵な計画だった。" },
  { word: "augment", pos: "動詞", meaning: "増大させる", example: "He augmented his income by teaching.", exampleJa: "彼は教えることで収入を増やした。" },
  { word: "auspicious", pos: "形容詞", meaning: "縁起の良い", example: "The project had an auspicious start.", exampleJa: "そのプロジェクトは幸先の良いスタートを切った。" },
  { word: "austere", pos: "形容詞", meaning: "厳格な、質素な", example: "He led an austere life.", exampleJa: "彼は質素な生活を送った。" },
  { word: "banal", pos: "形容詞", meaning: "ありきたりの、陳腐な", example: "The movie had a banal plot.", exampleJa: "その映画は陳腐な筋書きだった。" },
  { word: "belligerent", pos: "形容詞", meaning: "好戦的な", example: "He became belligerent after drinking.", exampleJa: "彼は酒を飲むと好戦的になった。" },
  { word: "benevolent", pos: "形容詞", meaning: "慈悲深い", example: "She is known for her benevolent deeds.", exampleJa: "彼女は慈悲深い行いで知られている。" },
  { word: "bolster", pos: "動詞", meaning: "支える、強化する", example: "The news bolstered his confidence.", exampleJa: "その知らせは彼の自信を強めた。" },
  { word: "brusque", pos: "形容詞", meaning: "ぶっきらぼうな", example: "Her brusque manner offended him.", exampleJa: "彼女のぶっきらぼうな態度が彼を不快にさせた。" },
  { word: "cajole", pos: "動詞", meaning: "おだてて〜させる", example: "He cajoled her into lending him money.", exampleJa: "彼は彼女をおだててお金を貸させた。" },
  { word: "candid", pos: "形容詞", meaning: "率直な", example: "She gave a candid answer.", exampleJa: "彼女は率直な答えを返した。" },
  { word: "capricious", pos: "形容詞", meaning: "気まぐれな", example: "The weather here is capricious.", exampleJa: "ここの天気は気まぐれだ。" },
  { word: "castigate", pos: "動詞", meaning: "厳しく非難する", example: "The critic castigated the novel.", exampleJa: "その批評家はその小説を厳しく非難した。" },
  { word: "circumvent", pos: "動詞", meaning: "回避する", example: "They tried to circumvent the law.", exampleJa: "彼らは法律を回避しようとした。" },
  { word: "clandestine", pos: "形容詞", meaning: "秘密の", example: "They held clandestine meetings.", exampleJa: "彼らは秘密の会合を開いた。" },
  { word: "coerce", pos: "動詞", meaning: "強要する", example: "He was coerced into signing.", exampleJa: "彼は強要されて署名した。" },
  { word: "cogent", pos: "形容詞", meaning: "説得力のある", example: "She made a cogent argument.", exampleJa: "彼女は説得力のある主張をした。" },
  { word: "complacent", pos: "形容詞", meaning: "自己満足の", example: "Don't become complacent about success.", exampleJa: "成功に自己満足してはいけない。" },
  { word: "conciliate", pos: "動詞", meaning: "なだめる、和解させる", example: "He tried to conciliate both sides.", exampleJa: "彼は両者を和解させようとした。" },
  { word: "condone", pos: "動詞", meaning: "大目に見る", example: "We cannot condone such behavior.", exampleJa: "そのような行為を大目に見ることはできない。" },
  { word: "conflagration", pos: "名詞", meaning: "大火", example: "The conflagration destroyed the entire village.", exampleJa: "大火事が村全体を破壊した。" },
  { word: "conspicuous", pos: "形容詞", meaning: "目立つ", example: "She was conspicuous in her red dress.", exampleJa: "彼女は赤いドレスで目立っていた。" },
  { word: "contentious", pos: "形容詞", meaning: "議論を呼ぶ", example: "It is a contentious issue.", exampleJa: "それは議論を呼ぶ問題だ。" },
  { word: "corroborate", pos: "動詞", meaning: "裏付ける", example: "Witnesses corroborated his story.", exampleJa: "目撃者たちが彼の話を裏付けた。" },
  { word: "cursory", pos: "形容詞", meaning: "ざっとした", example: "He gave the report a cursory glance.", exampleJa: "彼は報告書をざっと見ただけだった。" },
  { word: "debilitate", pos: "動詞", meaning: "衰弱させる", example: "The illness debilitated him.", exampleJa: "その病気は彼を衰弱させた。" },
  { word: "deleterious", pos: "形容詞", meaning: "有害な", example: "Smoking has deleterious effects on health.", exampleJa: "喫煙は健康に有害な影響を与える。" },
  { word: "denounce", pos: "動詞", meaning: "公然と非難する", example: "The leader denounced the attack.", exampleJa: "指導者は攻撃を公然と非難した。" },
  { word: "deride", pos: "動詞", meaning: "あざ笑う", example: "They derided his ideas.", exampleJa: "彼らは彼の考えをあざ笑った。" },
  { word: "despondent", pos: "形容詞", meaning: "落胆した", example: "He felt despondent after the loss.", exampleJa: "敗北の後、彼は落胆した。" },
  { word: "diligent", pos: "形容詞", meaning: "勤勉な", example: "She is a diligent worker.", exampleJa: "彼女は勤勉な働き手だ。" },
  { word: "disparage", pos: "動詞", meaning: "けなす", example: "Don't disparage his efforts.", exampleJa: "彼の努力をけなすな。" },
  { word: "disparity", pos: "名詞", meaning: "格差、相違", example: "There is a wide disparity in income.", exampleJa: "収入には大きな格差がある。" },
  { word: "dogmatic", pos: "形容詞", meaning: "独断的な", example: "He is dogmatic in his views.", exampleJa: "彼は自分の見解について独断的だ。" },
  { word: "ebullient", pos: "形容詞", meaning: "熱狂的な、快活な", example: "She was ebullient after the victory.", exampleJa: "勝利の後、彼女は熱狂的だった。" },
  { word: "eloquent", pos: "形容詞", meaning: "雄弁な", example: "He gave an eloquent speech.", exampleJa: "彼は雄弁なスピーチをした。" },
  { word: "elucidate", pos: "動詞", meaning: "明らかにする", example: "Please elucidate your point.", exampleJa: "あなたの論点を明らかにしてください。" },
  { word: "emulate", pos: "動詞", meaning: "見習う", example: "Children often emulate their parents.", exampleJa: "子供はしばしば親を見習う。" },
  { word: "endeavor", pos: "動詞/名詞", meaning: "努力(する)", example: "We endeavor to provide the best service.", exampleJa: "私たちは最高のサービスを提供するよう努める。" },
  { word: "enervate", pos: "動詞", meaning: "衰弱させる", example: "The heat enervated us all.", exampleJa: "暑さが私たち全員を衰弱させた。" },
  { word: "ephemeral", pos: "形容詞", meaning: "短命の、はかない", example: "Fame can be ephemeral.", exampleJa: "名声ははかないものだ。" },
  { word: "equivocal", pos: "形容詞", meaning: "曖昧な", example: "His reply was equivocal.", exampleJa: "彼の返答は曖昧だった。" },
  { word: "erudite", pos: "形容詞", meaning: "博学な", example: "He is an erudite scholar.", exampleJa: "彼は博学な学者だ。" },
  { word: "esoteric", pos: "形容詞", meaning: "難解な", example: "The book is too esoteric for beginners.", exampleJa: "その本は初心者には難解すぎる。" },
  { word: "evasive", pos: "形容詞", meaning: "言い逃れの", example: "He gave an evasive answer.", exampleJa: "彼は言い逃れの答えをした。" },
  { word: "exacerbate", pos: "動詞", meaning: "悪化させる", example: "Stress can exacerbate the illness.", exampleJa: "ストレスはその病気を悪化させうる。" },
  { word: "exonerate", pos: "動詞", meaning: "無罪を証明する", example: "The evidence exonerated him.", exampleJa: "証拠が彼の無罪を証明した。" },
  { word: "exorbitant", pos: "形容詞", meaning: "法外な", example: "The hotel charges exorbitant prices.", exampleJa: "そのホテルは法外な料金を請求する。" },
  { word: "expedite", pos: "動詞", meaning: "促進する", example: "Please expedite the delivery.", exampleJa: "配達を早めてください。" },
  { word: "extol", pos: "動詞", meaning: "称賛する", example: "She extolled his virtues.", exampleJa: "彼女は彼の美徳を称賛した。" },
  { word: "fastidious", pos: "形容詞", meaning: "気難しい、几帳面な", example: "He is fastidious about cleanliness.", exampleJa: "彼は清潔さについて几帳面だ。" },
  { word: "feasible", pos: "形容詞", meaning: "実行可能な", example: "Is this plan feasible?", exampleJa: "この計画は実行可能か？" },
  { word: "flagrant", pos: "形容詞", meaning: "目に余る", example: "It was a flagrant violation of the rules.", exampleJa: "それは目に余る規則違反だった。" },
  { word: "fortuitous", pos: "形容詞", meaning: "偶然の、幸運な", example: "Our meeting was fortuitous.", exampleJa: "私たちの出会いは偶然だった。" },
  { word: "frugal", pos: "形容詞", meaning: "倹約な", example: "She leads a frugal lifestyle.", exampleJa: "彼女は倹約な生活を送っている。" },
  { word: "garrulous", pos: "形容詞", meaning: "おしゃべりな", example: "My neighbor is garrulous.", exampleJa: "隣人はおしゃべりだ。" },
  { word: "gregarious", pos: "形容詞", meaning: "社交的な", example: "She is a gregarious person.", exampleJa: "彼女は社交的な人だ。" },
  { word: "hackneyed", pos: "形容詞", meaning: "使い古された", example: "He used hackneyed phrases.", exampleJa: "彼は使い古された言い回しを使った。" },
  { word: "hamper", pos: "動詞", meaning: "妨げる", example: "Heavy rain hampered the rescue.", exampleJa: "大雨が救助を妨げた。" },
  { word: "hapless", pos: "形容詞", meaning: "不運な", example: "The hapless traveler lost his luggage.", exampleJa: "不運な旅行者は荷物を失った。" },
  { word: "harbinger", pos: "名詞", meaning: "前兆", example: "Swallows are a harbinger of spring.", exampleJa: "ツバメは春の前兆だ。" },
  { word: "haughty", pos: "形容詞", meaning: "傲慢な", example: "He spoke in a haughty tone.", exampleJa: "彼は傲慢な口調で話した。" },
  { word: "hedonistic", pos: "形容詞", meaning: "快楽主義の", example: "He lived a hedonistic lifestyle.", exampleJa: "彼は快楽主義的な生活を送った。" },
  { word: "idiosyncrasy", pos: "名詞", meaning: "特異な癖", example: "Everyone has their idiosyncrasies.", exampleJa: "誰にでも特異な癖がある。" },
  { word: "impeccable", pos: "形容詞", meaning: "非の打ち所がない", example: "His manners are impeccable.", exampleJa: "彼のマナーは非の打ち所がない。" },
  { word: "impecunious", pos: "形容詞", meaning: "金のない", example: "He was an impecunious student.", exampleJa: "彼は金のない学生だった。" },
  { word: "imperious", pos: "形容詞", meaning: "横柄な", example: "She had an imperious manner.", exampleJa: "彼女は横柄な態度をとった。" },
  { word: "impetuous", pos: "形容詞", meaning: "衝動的な", example: "He made an impetuous decision.", exampleJa: "彼は衝動的な決定をした。" },
  { word: "implacable", pos: "形容詞", meaning: "容赦ない", example: "She is an implacable opponent.", exampleJa: "彼女は容赦ない敵対者だ。" },
  { word: "inadvertent", pos: "形容詞", meaning: "うっかりした", example: "It was an inadvertent mistake.", exampleJa: "それはうっかりした間違いだった。" },
  { word: "incessant", pos: "形容詞", meaning: "絶え間ない", example: "The incessant noise annoyed me.", exampleJa: "絶え間ない騒音が私を悩ませた。" },
  { word: "incongruous", pos: "形容詞", meaning: "不似合いな", example: "His tie was incongruous with the suit.", exampleJa: "彼のネクタイはスーツと不似合いだった。" },
  { word: "indolent", pos: "形容詞", meaning: "怠惰な", example: "He is indolent by nature.", exampleJa: "彼は生来怠惰だ。" },
  { word: "ineffable", pos: "形容詞", meaning: "言葉にできない", example: "She felt ineffable joy.", exampleJa: "彼女は言葉にできない喜びを感じた。" },
  { word: "inscrutable", pos: "形容詞", meaning: "不可解な", example: "His expression was inscrutable.", exampleJa: "彼の表情は不可解だった。" },
  { word: "insidious", pos: "形容詞", meaning: "陰険な、潜行性の", example: "It is an insidious disease.", exampleJa: "それは潜行性の病気だ。" },
  { word: "intrepid", pos: "形容詞", meaning: "大胆不敵な", example: "The intrepid explorer set off.", exampleJa: "大胆不敵な探検家は出発した。" },
  { word: "inundate", pos: "動詞", meaning: "氾濫させる、殺到させる", example: "We were inundated with requests.", exampleJa: "私たちは依頼が殺到した。" },
  { word: "irascible", pos: "形容詞", meaning: "怒りっぽい", example: "He is an irascible old man.", exampleJa: "彼は怒りっぽい老人だ。" },
  { word: "jocular", pos: "形容詞", meaning: "おどけた", example: "He made a jocular remark.", exampleJa: "彼はおどけた発言をした。" },
  { word: "laconic", pos: "形容詞", meaning: "寡黙な、簡潔な", example: "He gave a laconic reply.", exampleJa: "彼は簡潔な返事をした。" },
  { word: "languid", pos: "形容詞", meaning: "気だるい", example: "She gave a languid smile.", exampleJa: "彼女は気だるい笑みを浮かべた。" },
  { word: "lethargic", pos: "形容詞", meaning: "無気力な", example: "I feel lethargic today.", exampleJa: "今日は無気力だ。" },
  { word: "loquacious", pos: "形容詞", meaning: "多弁な", example: "She became loquacious after a drink.", exampleJa: "彼女は一杯飲んだ後多弁になった。" },
  { word: "lucid", pos: "形容詞", meaning: "明快な", example: "His explanation was lucid.", exampleJa: "彼の説明は明快だった。" },
  { word: "magnanimous", pos: "形容詞", meaning: "寛大な", example: "He was magnanimous in victory.", exampleJa: "彼は勝利に対して寛大だった。" },
  { word: "malevolent", pos: "形容詞", meaning: "悪意のある", example: "She gave him a malevolent look.", exampleJa: "彼女は彼に悪意のある目を向けた。" },
  { word: "meticulous", pos: "形容詞", meaning: "細心の注意を払う", example: "He is meticulous about details.", exampleJa: "彼は細部について細心の注意を払う。" },
  { word: "mitigate", pos: "動詞", meaning: "和らげる", example: "Measures to mitigate climate change.", exampleJa: "気候変動を和らげる対策。" },
  { word: "mundane", pos: "形容詞", meaning: "平凡な", example: "Daily life can seem mundane.", exampleJa: "日常生活は平凡に感じられる。" },
  { word: "nefarious", pos: "形容詞", meaning: "極悪な", example: "He had nefarious intentions.", exampleJa: "彼は極悪な意図を持っていた。" },
  { word: "obfuscate", pos: "動詞", meaning: "分かりにくくする", example: "He tried to obfuscate the issue.", exampleJa: "彼は問題を分かりにくくしようとした。" },
  { word: "obsequious", pos: "形容詞", meaning: "こびへつらう", example: "He was obsequious to his boss.", exampleJa: "彼は上司にこびへつらった。" },
  { word: "obstinate", pos: "形容詞", meaning: "頑固な", example: "He is obstinate in his opinions.", exampleJa: "彼は意見が頑固だ。" },
  { word: "ostentatious", pos: "形容詞", meaning: "見せびらかす", example: "She wore ostentatious jewelry.", exampleJa: "彼女は見せびらかすような宝石を身につけた。" },
  { word: "palpable", pos: "形容詞", meaning: "明白な", example: "The tension was palpable.", exampleJa: "緊張は明白だった。" },
  { word: "paltry", pos: "形容詞", meaning: "わずかな", example: "He was paid a paltry sum.", exampleJa: "彼はわずかな金額しか支払われなかった。" },
  { word: "partisan", pos: "形容詞/名詞", meaning: "党派心の強い(人)", example: "The media is too partisan.", exampleJa: "メディアは党派心が強すぎる。" },
  { word: "paucity", pos: "名詞", meaning: "欠乏", example: "There is a paucity of evidence.", exampleJa: "証拠が欠乏している。" },
  { word: "pensive", pos: "形容詞", meaning: "物思いにふけった", example: "He sat in a pensive mood.", exampleJa: "彼は物思いにふけった気分で座っていた。" },
  { word: "perfunctory", pos: "形容詞", meaning: "おざなりの", example: "He gave a perfunctory nod.", exampleJa: "彼はおざなりにうなずいた。" },
  { word: "pernicious", pos: "形容詞", meaning: "有害な", example: "Pernicious rumors spread quickly.", exampleJa: "有害な噂はすぐに広まる。" },
  { word: "perspicacious", pos: "形容詞", meaning: "洞察力のある", example: "She is a perspicacious judge of character.", exampleJa: "彼女は人物の洞察力に優れている。" },
  { word: "pertinent", pos: "形容詞", meaning: "関連した、適切な", example: "Please ask pertinent questions.", exampleJa: "関連した質問をしてください。" },
  { word: "pervasive", pos: "形容詞", meaning: "広く浸透した", example: "Corruption is pervasive.", exampleJa: "腐敗が広く浸透している。" },
  { word: "petulant", pos: "形容詞", meaning: "短気な", example: "He gave a petulant reply.", exampleJa: "彼は短気な返事をした。" },
  { word: "placate", pos: "動詞", meaning: "なだめる", example: "He tried to placate his angry wife.", exampleJa: "彼は怒った妻をなだめようとした。" },
  { word: "precarious", pos: "形容詞", meaning: "危なっかしい", example: "They are in a precarious situation.", exampleJa: "彼らは危なっかしい状況にある。" },
  { word: "precocious", pos: "形容詞", meaning: "早熟な", example: "She is a precocious child.", exampleJa: "彼女は早熟な子供だ。" },
  { word: "procrastinate", pos: "動詞", meaning: "先延ばしにする", example: "Don't procrastinate your studies.", exampleJa: "勉強を先延ばしにするな。" },
  { word: "profound", pos: "形容詞", meaning: "深遠な", example: "His words had a profound effect.", exampleJa: "彼の言葉は深遠な影響を与えた。" },
  { word: "proliferate", pos: "動詞", meaning: "急増する", example: "Fake news proliferates online.", exampleJa: "フェイクニュースはネットで急増する。" },
  { word: "prudent", pos: "形容詞", meaning: "慎重な", example: "It is prudent to save money.", exampleJa: "お金を貯めるのは慎重なことだ。" },
  { word: "pugnacious", pos: "形容詞", meaning: "けんか腰の", example: "He has a pugnacious personality.", exampleJa: "彼はけんか腰の性格だ。" },
  { word: "quell", pos: "動詞", meaning: "鎮める", example: "The police quelled the riot.", exampleJa: "警察は暴動を鎮めた。" },
  { word: "querulous", pos: "形容詞", meaning: "不平ばかり言う", example: "She has a querulous tone.", exampleJa: "彼女は不平ばかり言う口調だ。" },
  { word: "quixotic", pos: "形容詞", meaning: "非現実的な、空想的な", example: "His plan seemed quixotic.", exampleJa: "彼の計画は非現実的に思えた。" },
  { word: "rancor", pos: "名詞", meaning: "深い恨み", example: "He spoke without rancor.", exampleJa: "彼は恨みもなく話した。" },
  { word: "rapacious", pos: "形容詞", meaning: "貪欲な", example: "The company is rapacious for profit.", exampleJa: "その会社は利益に貪欲だ。" },
  { word: "reclusive", pos: "形容詞", meaning: "隠遁的な", example: "The author is reclusive.", exampleJa: "その作家は隠遁的だ。" },
  { word: "recondite", pos: "形容詞", meaning: "難解な", example: "The topic is recondite.", exampleJa: "その話題は難解だ。" },
  { word: "relinquish", pos: "動詞", meaning: "手放す", example: "He had to relinquish his position.", exampleJa: "彼は地位を手放さなければならなかった。" },
  { word: "reprehensible", pos: "形容詞", meaning: "非難に値する", example: "His behavior was reprehensible.", exampleJa: "彼の行動は非難に値した。" },
  { word: "reprimand", pos: "動詞/名詞", meaning: "叱責(する)", example: "The boss reprimanded him.", exampleJa: "上司は彼を叱責した。" },
  { word: "resilient", pos: "形容詞", meaning: "回復力のある", example: "Children are remarkably resilient.", exampleJa: "子供は驚くほど回復力がある。" },
  { word: "reticent", pos: "形容詞", meaning: "寡黙な", example: "She is reticent about her past.", exampleJa: "彼女は過去について寡黙だ。" },
  { word: "sagacious", pos: "形容詞", meaning: "賢明な", example: "He is a sagacious leader.", exampleJa: "彼は賢明なリーダーだ。" },
  { word: "sanguine", pos: "形容詞", meaning: "楽観的な", example: "She is sanguine about the future.", exampleJa: "彼女は未来について楽観的だ。" },
  { word: "sanction", pos: "動詞/名詞", meaning: "制裁/認可(する)", example: "The UN imposed sanctions.", exampleJa: "国連は制裁を課した。" },
  { word: "scrupulous", pos: "形容詞", meaning: "良心的な、綿密な", example: "He is scrupulous about honesty.", exampleJa: "彼は正直さについて良心的だ。" },
  { word: "serendipity", pos: "名詞", meaning: "偶然の幸運な発見", example: "Our meeting was pure serendipity.", exampleJa: "私たちの出会いは全くの偶然の幸運だった。" },
  { word: "spurious", pos: "形容詞", meaning: "偽の", example: "He made a spurious claim.", exampleJa: "彼は偽の主張をした。" },
  { word: "staunch", pos: "形容詞", meaning: "忠実な", example: "She is a staunch supporter.", exampleJa: "彼女は忠実な支持者だ。" },
  { word: "stoic", pos: "形容詞", meaning: "平然とした、禁欲的な", example: "He remained stoic in the face of danger.", exampleJa: "彼は危険に直面しても平然としていた。" },
  { word: "strident", pos: "形容詞", meaning: "耳障りな、強硬な", example: "She made strident demands.", exampleJa: "彼女は強硬な要求をした。" },
  { word: "succinct", pos: "形容詞", meaning: "簡潔な", example: "Please be succinct.", exampleJa: "簡潔にお願いします。" },
  { word: "superfluous", pos: "形容詞", meaning: "余分な", example: "These details are superfluous.", exampleJa: "これらの詳細は余分だ。" },
  { word: "surreptitious", pos: "形容詞", meaning: "こっそりした", example: "He took a surreptitious glance.", exampleJa: "彼はこっそり一瞥した。" },
  { word: "sycophant", pos: "名詞", meaning: "おべっか使い", example: "He is surrounded by sycophants.", exampleJa: "彼はおべっか使いに囲まれている。" },
  { word: "taciturn", pos: "形容詞", meaning: "無口な", example: "He is a taciturn man.", exampleJa: "彼は無口な男だ。" },
  { word: "tangible", pos: "形容詞", meaning: "実体のある、明白な", example: "We need tangible results.", exampleJa: "私たちには実体のある結果が必要だ。" },
  { word: "tenacious", pos: "形容詞", meaning: "粘り強い", example: "She is a tenacious researcher.", exampleJa: "彼女は粘り強い研究者だ。" },
  { word: "tentative", pos: "形容詞", meaning: "暫定的な", example: "We reached a tentative agreement.", exampleJa: "私たちは暫定的な合意に達した。" },
  { word: "timorous", pos: "形容詞", meaning: "臆病な", example: "He gave a timorous reply.", exampleJa: "彼は臆病な返事をした。" },
  { word: "tractable", pos: "形容詞", meaning: "御しやすい", example: "The problem is tractable.", exampleJa: "その問題は御しやすい。" },
  { word: "truculent", pos: "形容詞", meaning: "けんか腰の", example: "He is in a truculent mood.", exampleJa: "彼はけんか腰の気分だ。" },
  { word: "ubiquitous", pos: "形容詞", meaning: "いたる所にある", example: "Smartphones are ubiquitous today.", exampleJa: "今やスマートフォンはいたる所にある。" },
  { word: "unfettered", pos: "形容詞", meaning: "制約のない", example: "She had unfettered access to the library.", exampleJa: "彼女は図書館に制約なく入れた。" },
  { word: "unprecedented", pos: "形容詞", meaning: "前例のない", example: "We face unprecedented challenges.", exampleJa: "私たちは前例のない課題に直面している。" },
  { word: "vacillate", pos: "動詞", meaning: "迷う、揺れ動く", example: "He vacillated between two options.", exampleJa: "彼は二つの選択肢の間で迷った。" },
  { word: "venerable", pos: "形容詞", meaning: "尊敬すべき", example: "He is a venerable scholar.", exampleJa: "彼は尊敬すべき学者だ。" },
  { word: "veracity", pos: "名詞", meaning: "真実性", example: "I doubt the veracity of his claim.", exampleJa: "私は彼の主張の真実性を疑う。" },
  { word: "verbose", pos: "形容詞", meaning: "冗長な", example: "His writing is too verbose.", exampleJa: "彼の文章は冗長すぎる。" },
  { word: "vex", pos: "動詞", meaning: "悩ませる", example: "The problem vexed the scientists.", exampleJa: "その問題は科学者を悩ませた。" },
  { word: "vilify", pos: "動詞", meaning: "中傷する", example: "The media vilified him.", exampleJa: "メディアは彼を中傷した。" },
  { word: "vindicate", pos: "動詞", meaning: "正当性を示す", example: "The results vindicated her theory.", exampleJa: "結果が彼女の理論の正当性を示した。" },
  { word: "vociferous", pos: "形容詞", meaning: "声高な", example: "He is a vociferous critic.", exampleJa: "彼は声高な批評家だ。" },
  { word: "wary", pos: "形容詞", meaning: "用心深い", example: "Be wary of strangers.", exampleJa: "見知らぬ人には用心しなさい。" },
  { word: "whimsical", pos: "形容詞", meaning: "気まぐれな", example: "She has a whimsical sense of humor.", exampleJa: "彼女は気まぐれなユーモアのセンスを持つ。" },
  { word: "zealous", pos: "形容詞", meaning: "熱心な", example: "He is a zealous advocate.", exampleJa: "彼は熱心な擁護者だ。" }
];
