const WORDS_2KYU = [
  { word: "accomplish", pos: "動詞", meaning: "成し遂げる", example: "She accomplished her goal after years of hard work.", exampleJa: "彼女は何年もの努力の末に目標を成し遂げた。" },
  { word: "accurate", pos: "形容詞", meaning: "正確な", example: "Please give me an accurate answer.", exampleJa: "正確な答えを教えてください。" },
  { word: "achieve", pos: "動詞", meaning: "達成する", example: "He achieved great success in his career.", exampleJa: "彼はキャリアで大きな成功を達成した。" },
  { word: "admit", pos: "動詞", meaning: "認める", example: "He admitted that he made a mistake.", exampleJa: "彼は自分が間違いを犯したと認めた。" },
  { word: "afford", pos: "動詞", meaning: "〜する余裕がある", example: "I can't afford a new car right now.", exampleJa: "今は新しい車を買う余裕がない。" },
  { word: "ancient", pos: "形容詞", meaning: "古代の", example: "They study ancient history at the university.", exampleJa: "彼らは大学で古代史を研究している。" },
  { word: "announce", pos: "動詞", meaning: "発表する", example: "The company announced a new product yesterday.", exampleJa: "その会社は昨日新製品を発表した。" },
  { word: "anxious", pos: "形容詞", meaning: "心配な、不安な", example: "She was anxious about the exam.", exampleJa: "彼女は試験のことが心配だった。" },
  { word: "apologize", pos: "動詞", meaning: "謝る", example: "He apologized for being late.", exampleJa: "彼は遅刻したことを謝った。" },
  { word: "appreciate", pos: "動詞", meaning: "感謝する、評価する", example: "I really appreciate your help.", exampleJa: "あなたの助けに本当に感謝しています。" },
  { word: "appropriate", pos: "形容詞", meaning: "適切な", example: "Please wear appropriate clothes for the interview.", exampleJa: "面接には適切な服装で来てください。" },
  { word: "approve", pos: "動詞", meaning: "承認する、賛成する", example: "The manager approved the plan.", exampleJa: "部長はその計画を承認した。" },
  { word: "argue", pos: "動詞", meaning: "議論する、主張する", example: "They argued about the best solution.", exampleJa: "彼らは最善の解決策について議論した。" },
  { word: "arrange", pos: "動詞", meaning: "手配する、整える", example: "I will arrange a meeting for next week.", exampleJa: "来週の会議を手配します。" },
  { word: "assist", pos: "動詞", meaning: "手伝う、支援する", example: "Can you assist me with this task?", exampleJa: "この作業を手伝ってくれますか。" },
  { word: "attempt", pos: "動詞/名詞", meaning: "試みる/試み", example: "She attempted to climb the mountain.", exampleJa: "彼女はその山に登ろうと試みた。" },
  { word: "attend", pos: "動詞", meaning: "出席する", example: "I will attend the conference tomorrow.", exampleJa: "明日その会議に出席します。" },
  { word: "attract", pos: "動詞", meaning: "引きつける", example: "The museum attracts many tourists.", exampleJa: "その博物館は多くの観光客を引きつける。" },
  { word: "available", pos: "形容詞", meaning: "利用できる", example: "This book is available at the library.", exampleJa: "この本は図書館で利用できる。" },
  { word: "avoid", pos: "動詞", meaning: "避ける", example: "You should avoid eating too much sugar.", exampleJa: "砂糖を取りすぎるのは避けるべきだ。" },
  { word: "aware", pos: "形容詞", meaning: "気づいている", example: "He was not aware of the rule.", exampleJa: "彼はその規則に気づいていなかった。" },
  { word: "behave", pos: "動詞", meaning: "振る舞う", example: "The children behaved well at the party.", exampleJa: "子供たちはパーティーでよく振る舞った。" },
  { word: "benefit", pos: "名詞/動詞", meaning: "利益(を得る)", example: "Many students benefit from this program.", exampleJa: "多くの生徒がこのプログラムから利益を得ている。" },
  { word: "borrow", pos: "動詞", meaning: "借りる", example: "May I borrow your pen?", exampleJa: "あなたのペンを借りてもいいですか。" },
  { word: "capture", pos: "動詞", meaning: "捕らえる", example: "The photo captured a beautiful moment.", exampleJa: "その写真は美しい瞬間をとらえた。" },
  { word: "celebrate", pos: "動詞", meaning: "祝う", example: "We celebrated her birthday last night.", exampleJa: "昨夜彼女の誕生日を祝った。" },
  { word: "challenge", pos: "名詞/動詞", meaning: "挑戦(する)", example: "Learning a new language is a big challenge.", exampleJa: "新しい言語を学ぶのは大きな挑戦だ。" },
  { word: "claim", pos: "動詞/名詞", meaning: "主張する/要求", example: "He claimed that he was innocent.", exampleJa: "彼は自分が無実だと主張した。" },
  { word: "colleague", pos: "名詞", meaning: "同僚", example: "My colleague helped me with the report.", exampleJa: "同僚がレポートを手伝ってくれた。" },
  { word: "compare", pos: "動詞", meaning: "比較する", example: "Compare the two products before buying.", exampleJa: "買う前に2つの製品を比較してください。" },
  { word: "compete", pos: "動詞", meaning: "競争する", example: "Many runners competed in the marathon.", exampleJa: "多くの走者がマラソンで競争した。" },
  { word: "complain", pos: "動詞", meaning: "不平を言う", example: "She complained about the noise.", exampleJa: "彼女は騒音について不平を言った。" },
  { word: "confident", pos: "形容詞", meaning: "自信のある", example: "He is confident about his skills.", exampleJa: "彼は自分の技能に自信がある。" },
  { word: "confirm", pos: "動詞", meaning: "確認する", example: "Please confirm your reservation.", exampleJa: "予約を確認してください。" },
  { word: "confuse", pos: "動詞", meaning: "混乱させる", example: "The directions confused me.", exampleJa: "その道案内は私を混乱させた。" },
  { word: "consider", pos: "動詞", meaning: "考慮する", example: "We need to consider all options.", exampleJa: "すべての選択肢を考慮する必要がある。" },
  { word: "consume", pos: "動詞", meaning: "消費する", example: "Cars consume a lot of fuel.", exampleJa: "車は多くの燃料を消費する。" },
  { word: "contain", pos: "動詞", meaning: "含む", example: "This drink contains sugar.", exampleJa: "この飲み物には砂糖が含まれている。" },
  { word: "convince", pos: "動詞", meaning: "納得させる", example: "He convinced me to join the team.", exampleJa: "彼は私をチームに加わるよう説得した。" },
  { word: "create", pos: "動詞", meaning: "作り出す", example: "The artist created a beautiful painting.", exampleJa: "その芸術家は美しい絵を作り出した。" },
  { word: "damage", pos: "名詞/動詞", meaning: "損害(を与える)", example: "The storm caused serious damage.", exampleJa: "嵐が深刻な損害を引き起こした。" },
  { word: "decide", pos: "動詞", meaning: "決める", example: "I decided to study abroad.", exampleJa: "私は留学することに決めた。" },
  { word: "declare", pos: "動詞", meaning: "宣言する、申告する", example: "The president declared a new policy.", exampleJa: "大統領は新しい方針を宣言した。" },
  { word: "decrease", pos: "動詞/名詞", meaning: "減少(する)", example: "Sales decreased last month.", exampleJa: "先月売上が減少した。" },
  { word: "deliver", pos: "動詞", meaning: "配達する、届ける", example: "They will deliver the package tomorrow.", exampleJa: "彼らは明日荷物を配達する。" },
  { word: "demand", pos: "動詞/名詞", meaning: "要求(する)", example: "Workers demanded higher wages.", exampleJa: "労働者はより高い賃金を要求した。" },
  { word: "deny", pos: "動詞", meaning: "否定する", example: "He denied the accusation.", exampleJa: "彼はその非難を否定した。" },
  { word: "depend", pos: "動詞", meaning: "頼る、〜次第である", example: "It depends on the weather.", exampleJa: "それは天気次第だ。" },
  { word: "describe", pos: "動詞", meaning: "描写する、説明する", example: "Can you describe what you saw?", exampleJa: "見たものを説明できますか。" },
  { word: "deserve", pos: "動詞", meaning: "〜に値する", example: "You deserve a reward for your effort.", exampleJa: "あなたの努力は報酬に値する。" },
  { word: "destroy", pos: "動詞", meaning: "破壊する", example: "The fire destroyed the building.", exampleJa: "火事がその建物を破壊した。" },
  { word: "develop", pos: "動詞", meaning: "発展させる、開発する", example: "The country is developing rapidly.", exampleJa: "その国は急速に発展している。" },
  { word: "discover", pos: "動詞", meaning: "発見する", example: "Scientists discovered a new planet.", exampleJa: "科学者たちは新しい惑星を発見した。" },
  { word: "discuss", pos: "動詞", meaning: "議論する", example: "Let's discuss the problem calmly.", exampleJa: "落ち着いて問題を議論しよう。" },
  { word: "divide", pos: "動詞", meaning: "分ける", example: "The teacher divided the class into groups.", exampleJa: "先生はクラスをグループに分けた。" },
  { word: "earn", pos: "動詞", meaning: "稼ぐ、得る", example: "He earns a good salary.", exampleJa: "彼は良い給料を稼いでいる。" },
  { word: "educate", pos: "動詞", meaning: "教育する", example: "Parents should educate their children.", exampleJa: "親は子供を教育すべきだ。" },
  { word: "effort", pos: "名詞", meaning: "努力", example: "Success requires effort.", exampleJa: "成功には努力が必要だ。" },
  { word: "emergency", pos: "名詞", meaning: "緊急事態", example: "Please call 911 in an emergency.", exampleJa: "緊急時には911に電話してください。" },
  { word: "employ", pos: "動詞", meaning: "雇う", example: "The company employs 500 people.", exampleJa: "その会社は500人を雇っている。" },
  { word: "encourage", pos: "動詞", meaning: "励ます", example: "My teacher encouraged me to try harder.", exampleJa: "先生は私にもっと頑張るよう励ましてくれた。" },
  { word: "enemy", pos: "名詞", meaning: "敵", example: "Cold weather is an enemy of plants.", exampleJa: "寒い天気は植物の敵だ。" },
  { word: "entire", pos: "形容詞", meaning: "全体の", example: "She ate the entire pizza.", exampleJa: "彼女はピザ全部を食べた。" },
  { word: "environment", pos: "名詞", meaning: "環境", example: "We must protect the environment.", exampleJa: "私たちは環境を守らなければならない。" },
  { word: "equal", pos: "形容詞", meaning: "等しい、平等な", example: "All people should have equal rights.", exampleJa: "すべての人が平等な権利を持つべきだ。" },
  { word: "escape", pos: "動詞", meaning: "逃げる", example: "The prisoner escaped last night.", exampleJa: "その囚人は昨夜逃走した。" },
  { word: "essential", pos: "形容詞", meaning: "必要不可欠な", example: "Water is essential for life.", exampleJa: "水は生命に不可欠だ。" },
  { word: "establish", pos: "動詞", meaning: "設立する、確立する", example: "They established a new company.", exampleJa: "彼らは新しい会社を設立した。" },
  { word: "estimate", pos: "動詞/名詞", meaning: "見積もる/見積もり", example: "The mechanic estimated the cost.", exampleJa: "整備士は費用を見積もった。" },
  { word: "evidence", pos: "名詞", meaning: "証拠", example: "There is no evidence of a crime.", exampleJa: "犯罪の証拠はない。" },
  { word: "examine", pos: "動詞", meaning: "調べる、診察する", example: "The doctor examined the patient.", exampleJa: "医者は患者を診察した。" },
  { word: "exchange", pos: "動詞/名詞", meaning: "交換(する)", example: "Can I exchange this shirt?", exampleJa: "このシャツを交換できますか。" },
  { word: "exist", pos: "動詞", meaning: "存在する", example: "Does life exist on other planets?", exampleJa: "他の惑星に生命は存在するのか。" },
  { word: "expand", pos: "動詞", meaning: "拡大する", example: "The business is expanding quickly.", exampleJa: "事業は急速に拡大している。" },
  { word: "experience", pos: "名詞/動詞", meaning: "経験(する)", example: "She has a lot of teaching experience.", exampleJa: "彼女は豊富な指導経験がある。" },
  { word: "explain", pos: "動詞", meaning: "説明する", example: "Please explain the problem again.", exampleJa: "もう一度問題を説明してください。" },
  { word: "explore", pos: "動詞", meaning: "探検する、探究する", example: "We want to explore new ideas.", exampleJa: "私たちは新しいアイデアを探究したい。" },
  { word: "express", pos: "動詞", meaning: "表現する", example: "She expressed her thanks clearly.", exampleJa: "彼女ははっきりと感謝を表現した。" },
  { word: "familiar", pos: "形容詞", meaning: "よく知っている", example: "This song sounds familiar.", exampleJa: "この曲は聞き覚えがある。" },
  { word: "focus", pos: "動詞/名詞", meaning: "集中(する)", example: "Focus on your work.", exampleJa: "自分の仕事に集中しなさい。" },
  { word: "forecast", pos: "名詞/動詞", meaning: "予報(する)", example: "The weather forecast says it will rain.", exampleJa: "天気予報は雨と言っている。" },
  { word: "former", pos: "形容詞", meaning: "前の、元の", example: "He is the former president of the club.", exampleJa: "彼はクラブの前会長だ。" },
  { word: "freedom", pos: "名詞", meaning: "自由", example: "They fought for freedom.", exampleJa: "彼らは自由のために戦った。" },
  { word: "generate", pos: "動詞", meaning: "生み出す", example: "Solar panels generate electricity.", exampleJa: "太陽光パネルは電気を生み出す。" },
  { word: "generation", pos: "名詞", meaning: "世代", example: "Each generation faces new challenges.", exampleJa: "各世代は新しい課題に直面する。" },
  { word: "government", pos: "名詞", meaning: "政府", example: "The government announced new rules.", exampleJa: "政府は新しい規則を発表した。" },
  { word: "graduate", pos: "動詞/名詞", meaning: "卒業する/卒業生", example: "She graduated from Tokyo University.", exampleJa: "彼女は東京大学を卒業した。" },
  { word: "grateful", pos: "形容詞", meaning: "感謝している", example: "I am grateful for your kindness.", exampleJa: "ご親切に感謝しています。" },
  { word: "guarantee", pos: "動詞/名詞", meaning: "保証(する)", example: "We guarantee the quality of our products.", exampleJa: "私たちは製品の品質を保証する。" },
  { word: "handle", pos: "動詞", meaning: "扱う、対処する", example: "She can handle difficult situations.", exampleJa: "彼女は難しい状況に対処できる。" },
  { word: "honest", pos: "形容詞", meaning: "正直な", example: "He is an honest person.", exampleJa: "彼は正直な人だ。" },
  { word: "identify", pos: "動詞", meaning: "特定する", example: "Can you identify the problem?", exampleJa: "問題を特定できますか。" },
  { word: "ignore", pos: "動詞", meaning: "無視する", example: "Don't ignore the warning signs.", exampleJa: "警告サインを無視してはいけない。" },
  { word: "imagine", pos: "動詞", meaning: "想像する", example: "Imagine a world without war.", exampleJa: "戦争のない世界を想像してごらん。" },
  { word: "immediate", pos: "形容詞", meaning: "即座の", example: "We need an immediate response.", exampleJa: "即座の対応が必要だ。" },
  { word: "improve", pos: "動詞", meaning: "改善する、上達する", example: "Her English has improved a lot.", exampleJa: "彼女の英語はとても上達した。" },
  { word: "include", pos: "動詞", meaning: "含む", example: "The price includes tax.", exampleJa: "価格には税金が含まれている。" },
  { word: "income", pos: "名詞", meaning: "収入", example: "His monthly income is stable.", exampleJa: "彼の月収は安定している。" },
  { word: "increase", pos: "動詞/名詞", meaning: "増加(する)", example: "Prices have increased this year.", exampleJa: "今年価格が上がった。" },
  { word: "indicate", pos: "動詞", meaning: "示す", example: "The sign indicates the right direction.", exampleJa: "その標識は正しい方向を示している。" },
  { word: "individual", pos: "名詞/形容詞", meaning: "個人(の)", example: "Each individual has different needs.", exampleJa: "各個人には異なるニーズがある。" },
  { word: "industry", pos: "名詞", meaning: "産業", example: "The car industry is changing.", exampleJa: "自動車産業は変化している。" },
  { word: "influence", pos: "名詞/動詞", meaning: "影響(を与える)", example: "His teacher had a big influence on him.", exampleJa: "彼の先生は彼に大きな影響を与えた。" },
  { word: "injury", pos: "名詞", meaning: "けが", example: "He recovered from his injury quickly.", exampleJa: "彼はけがから早く回復した。" },
  { word: "instead", pos: "副詞", meaning: "代わりに", example: "I will have tea instead of coffee.", exampleJa: "コーヒーの代わりに紅茶を飲みます。" },
  { word: "introduce", pos: "動詞", meaning: "紹介する、導入する", example: "Let me introduce my friend to you.", exampleJa: "私の友達を紹介させてください。" },
  { word: "invent", pos: "動詞", meaning: "発明する", example: "Edison invented many useful things.", exampleJa: "エジソンは多くの便利なものを発明した。" },
  { word: "invite", pos: "動詞", meaning: "招待する", example: "They invited us to the party.", exampleJa: "彼らは私たちをパーティーに招待した。" },
  { word: "involve", pos: "動詞", meaning: "関わる、含む", example: "The project involves many people.", exampleJa: "そのプロジェクトは多くの人が関わっている。" },
  { word: "judge", pos: "動詞/名詞", meaning: "判断する/裁判官", example: "Don't judge a book by its cover.", exampleJa: "見かけで判断してはいけない。" },
  { word: "likely", pos: "形容詞/副詞", meaning: "ありそうな", example: "It is likely to rain tomorrow.", exampleJa: "明日は雨が降りそうだ。" },
  { word: "maintain", pos: "動詞", meaning: "維持する", example: "It is important to maintain good health.", exampleJa: "健康を維持することは大切だ。" },
  { word: "major", pos: "形容詞", meaning: "主要な", example: "Tokyo is a major city in Asia.", exampleJa: "東京はアジアの主要な都市だ。" },
  { word: "manage", pos: "動詞", meaning: "管理する、なんとかする", example: "She manages the whole team.", exampleJa: "彼女はチーム全体を管理している。" },
  { word: "measure", pos: "動詞/名詞", meaning: "測る/対策", example: "Please measure the length of the desk.", exampleJa: "机の長さを測ってください。" },
  { word: "mention", pos: "動詞", meaning: "言及する", example: "He mentioned your name in the meeting.", exampleJa: "彼は会議であなたの名前を出した。" },
  { word: "method", pos: "名詞", meaning: "方法", example: "This is the best method to solve it.", exampleJa: "これがそれを解決する最良の方法だ。" },
  { word: "notice", pos: "動詞/名詞", meaning: "気づく/通知", example: "I noticed a strange sound.", exampleJa: "奇妙な音に気づいた。" },
  { word: "observe", pos: "動詞", meaning: "観察する", example: "Scientists observe animal behavior.", exampleJa: "科学者は動物の行動を観察する。" },
  { word: "obtain", pos: "動詞", meaning: "得る、入手する", example: "She obtained a driver's license.", exampleJa: "彼女は運転免許を取得した。" },
  { word: "occasion", pos: "名詞", meaning: "機会、場合", example: "I met him on several occasions.", exampleJa: "何度か彼に会ったことがある。" },
  { word: "offer", pos: "動詞/名詞", meaning: "申し出る/提案", example: "He offered to help me.", exampleJa: "彼は手伝おうと申し出た。" },
  { word: "opinion", pos: "名詞", meaning: "意見", example: "What is your opinion?", exampleJa: "あなたの意見は何ですか。" },
  { word: "opportunity", pos: "名詞", meaning: "機会", example: "This is a great opportunity.", exampleJa: "これは素晴らしい機会だ。" },
  { word: "organize", pos: "動詞", meaning: "組織する、整理する", example: "I need to organize my desk.", exampleJa: "机を整理する必要がある。" },
  { word: "original", pos: "形容詞", meaning: "元の、独創的な", example: "This is the original version.", exampleJa: "これは元のバージョンだ。" },
  { word: "patient", pos: "形容詞/名詞", meaning: "忍耐強い/患者", example: "Please be patient with the children.", exampleJa: "子供に辛抱強く接してください。" },
  { word: "perform", pos: "動詞", meaning: "実行する、演じる", example: "The band performed at the festival.", exampleJa: "バンドはフェスティバルで演奏した。" },
  { word: "permit", pos: "動詞/名詞", meaning: "許可(する)", example: "Smoking is not permitted here.", exampleJa: "ここでは喫煙は許可されていない。" },
  { word: "persuade", pos: "動詞", meaning: "説得する", example: "She persuaded him to come.", exampleJa: "彼女は彼に来るよう説得した。" },
  { word: "positive", pos: "形容詞", meaning: "前向きな、確かな", example: "Try to stay positive.", exampleJa: "前向きでいるようにしなさい。" },
  { word: "possibility", pos: "名詞", meaning: "可能性", example: "There is a possibility of rain.", exampleJa: "雨の可能性がある。" },
  { word: "predict", pos: "動詞", meaning: "予測する", example: "It's hard to predict the future.", exampleJa: "未来を予測するのは難しい。" },
  { word: "prefer", pos: "動詞", meaning: "〜を好む", example: "I prefer tea to coffee.", exampleJa: "コーヒーより紅茶の方が好きだ。" },
  { word: "prepare", pos: "動詞", meaning: "準備する", example: "She prepared dinner for the guests.", exampleJa: "彼女は客のために夕食を準備した。" },
  { word: "prevent", pos: "動詞", meaning: "防ぐ", example: "Exercise helps prevent illness.", exampleJa: "運動は病気を防ぐのに役立つ。" },
  { word: "previous", pos: "形容詞", meaning: "以前の", example: "She worked at a previous company.", exampleJa: "彼女は以前の会社で働いていた。" },
  { word: "process", pos: "名詞/動詞", meaning: "過程、処理(する)", example: "Learning is a long process.", exampleJa: "学ぶことは長い過程だ。" },
  { word: "produce", pos: "動詞", meaning: "生産する", example: "This factory produces cars.", exampleJa: "この工場は車を生産している。" },
  { word: "progress", pos: "名詞/動詞", meaning: "進歩(する)", example: "He is making good progress.", exampleJa: "彼は順調に進歩している。" },
  { word: "protect", pos: "動詞", meaning: "守る", example: "We must protect nature.", exampleJa: "自然を守らなければならない。" },
  { word: "provide", pos: "動詞", meaning: "提供する", example: "The hotel provides free breakfast.", exampleJa: "そのホテルは無料の朝食を提供している。" },
  { word: "publish", pos: "動詞", meaning: "出版する", example: "He published his first book last year.", exampleJa: "彼は去年最初の本を出版した。" },
  { word: "quality", pos: "名詞", meaning: "品質", example: "This product has high quality.", exampleJa: "この製品は高品質だ。" },
  { word: "realize", pos: "動詞", meaning: "気づく、実現する", example: "I realized I was wrong.", exampleJa: "自分が間違っていたと気づいた。" },
  { word: "receive", pos: "動詞", meaning: "受け取る", example: "I received a gift from her.", exampleJa: "彼女からプレゼントを受け取った。" },
  { word: "recent", pos: "形容詞", meaning: "最近の", example: "In recent years, technology has changed fast.", exampleJa: "近年、技術は急速に変化した。" },
  { word: "recognize", pos: "動詞", meaning: "認識する、識別する", example: "I didn't recognize him at first.", exampleJa: "最初彼だと気づかなかった。" },
  { word: "recommend", pos: "動詞", meaning: "勧める", example: "I recommend this restaurant.", exampleJa: "このレストランをお勧めします。" },
  { word: "reduce", pos: "動詞", meaning: "減らす", example: "Please reduce the volume.", exampleJa: "音量を下げてください。" },
  { word: "refer", pos: "動詞", meaning: "参照する、言及する", example: "Please refer to the manual.", exampleJa: "マニュアルを参照してください。" },
  { word: "refuse", pos: "動詞", meaning: "断る", example: "He refused the invitation.", exampleJa: "彼はその招待を断った。" },
  { word: "remain", pos: "動詞", meaning: "残る、〜のままでいる", example: "Please remain seated.", exampleJa: "席に座ったままでいてください。" },
  { word: "remind", pos: "動詞", meaning: "思い出させる", example: "This song reminds me of my childhood.", exampleJa: "この曲は子供時代を思い出させる。" },
  { word: "remove", pos: "動詞", meaning: "取り除く", example: "Please remove your shoes here.", exampleJa: "ここで靴を脱いでください。" },
  { word: "repair", pos: "動詞/名詞", meaning: "修理(する)", example: "He repaired the broken chair.", exampleJa: "彼は壊れた椅子を修理した。" },
  { word: "replace", pos: "動詞", meaning: "取り替える", example: "We need to replace the old battery.", exampleJa: "古い電池を交換する必要がある。" },
  { word: "represent", pos: "動詞", meaning: "代表する、表す", example: "She represents our school in the contest.", exampleJa: "彼女はコンテストで学校を代表する。" },
  { word: "require", pos: "動詞", meaning: "必要とする", example: "This job requires good English skills.", exampleJa: "この仕事は高い英語力を必要とする。" },
  { word: "research", pos: "名詞/動詞", meaning: "研究(する)", example: "She is doing research on cancer.", exampleJa: "彼女はがんの研究をしている。" },
  { word: "respect", pos: "動詞/名詞", meaning: "尊敬(する)", example: "I respect my parents.", exampleJa: "私は両親を尊敬している。" },
  { word: "responsible", pos: "形容詞", meaning: "責任のある", example: "Who is responsible for this?", exampleJa: "これは誰の責任ですか。" },
  { word: "result", pos: "名詞/動詞", meaning: "結果(生じる)", example: "The test results were good.", exampleJa: "試験結果は良かった。" },
  { word: "reveal", pos: "動詞", meaning: "明らかにする", example: "He finally revealed the truth.", exampleJa: "彼はついに真実を明らかにした。" },
  { word: "satisfy", pos: "動詞", meaning: "満足させる", example: "The meal satisfied us.", exampleJa: "その食事は私たちを満足させた。" },
  { word: "scholarship", pos: "名詞", meaning: "奨学金", example: "She received a scholarship.", exampleJa: "彼女は奨学金を受けた。" },
  { word: "select", pos: "動詞", meaning: "選ぶ", example: "Please select one option.", exampleJa: "1つの選択肢を選んでください。" },
  { word: "separate", pos: "動詞/形容詞", meaning: "分ける/別々の", example: "Please separate the trash.", exampleJa: "ゴミを分別してください。" },
  { word: "serious", pos: "形容詞", meaning: "深刻な、真剣な", example: "This is a serious problem.", exampleJa: "これは深刻な問題だ。" },
  { word: "share", pos: "動詞", meaning: "共有する", example: "Let's share the food.", exampleJa: "食べ物を分け合おう。" },
  { word: "similar", pos: "形容詞", meaning: "似ている", example: "Their voices sound similar.", exampleJa: "彼らの声は似て聞こえる。" },
  { word: "situation", pos: "名詞", meaning: "状況", example: "The situation is getting worse.", exampleJa: "状況は悪化している。" },
  { word: "society", pos: "名詞", meaning: "社会", example: "We live in a modern society.", exampleJa: "私たちは現代社会に生きている。" },
  { word: "solve", pos: "動詞", meaning: "解決する", example: "He solved the math problem quickly.", exampleJa: "彼はすぐに数学の問題を解いた。" },
  { word: "source", pos: "名詞", meaning: "源、情報源", example: "The sun is a source of energy.", exampleJa: "太陽はエネルギー源だ。" },
  { word: "specific", pos: "形容詞", meaning: "具体的な、特定の", example: "Please give me specific examples.", exampleJa: "具体的な例を挙げてください。" },
  { word: "spread", pos: "動詞", meaning: "広がる、広げる", example: "The news spread quickly.", exampleJa: "ニュースは急速に広がった。" },
  { word: "standard", pos: "名詞/形容詞", meaning: "基準(の)", example: "This product meets the standard.", exampleJa: "この製品は基準を満たしている。" },
  { word: "succeed", pos: "動詞", meaning: "成功する", example: "If you try hard, you will succeed.", exampleJa: "一生懸命やれば成功する。" },
  { word: "sudden", pos: "形容詞", meaning: "突然の", example: "There was a sudden change in the weather.", exampleJa: "天気に突然の変化があった。" },
  { word: "sufficient", pos: "形容詞", meaning: "十分な", example: "We have sufficient food for the trip.", exampleJa: "旅行に十分な食料がある。" },
  { word: "suggest", pos: "動詞", meaning: "提案する", example: "He suggested going to the beach.", exampleJa: "彼はビーチに行くことを提案した。" },
  { word: "support", pos: "動詞/名詞", meaning: "支える、支援(する)", example: "Thank you for your support.", exampleJa: "ご支援ありがとうございます。" },
  { word: "suppose", pos: "動詞", meaning: "思う、推測する", example: "I suppose you are right.", exampleJa: "あなたが正しいと思う。" },
  { word: "survive", pos: "動詞", meaning: "生き残る", example: "Only a few survived the accident.", exampleJa: "事故で生き残ったのはわずかだった。" },
  { word: "suspect", pos: "動詞/名詞", meaning: "疑う/容疑者", example: "The police suspected him.", exampleJa: "警察は彼を疑った。" },
  { word: "system", pos: "名詞", meaning: "システム、制度", example: "This computer system is old.", exampleJa: "このコンピューターシステムは古い。" },
  { word: "talent", pos: "名詞", meaning: "才能", example: "She has a talent for music.", exampleJa: "彼女には音楽の才能がある。" },
  { word: "technique", pos: "名詞", meaning: "技術", example: "He learned new techniques.", exampleJa: "彼は新しい技術を学んだ。" },
  { word: "tend", pos: "動詞", meaning: "〜する傾向がある", example: "She tends to arrive early.", exampleJa: "彼女は早く着く傾向がある。" },
  { word: "tradition", pos: "名詞", meaning: "伝統", example: "This is a local tradition.", exampleJa: "これは地元の伝統だ。" },
  { word: "traffic", pos: "名詞", meaning: "交通", example: "The traffic is heavy today.", exampleJa: "今日は交通が混雑している。" },
  { word: "translate", pos: "動詞", meaning: "翻訳する", example: "Can you translate this letter?", exampleJa: "この手紙を翻訳できますか。" },
  { word: "treat", pos: "動詞", meaning: "扱う、治療する", example: "He treats everyone kindly.", exampleJa: "彼は誰にでも優しく接する。" },
  { word: "trust", pos: "動詞/名詞", meaning: "信頼(する)", example: "I trust my best friend.", exampleJa: "私は親友を信頼している。" },
  { word: "unique", pos: "形容詞", meaning: "独特の", example: "Every person is unique.", exampleJa: "すべての人はそれぞれ独特だ。" },
  { word: "various", pos: "形容詞", meaning: "様々な", example: "The store sells various items.", exampleJa: "その店は様々な品物を売っている。" },
  { word: "victim", pos: "名詞", meaning: "犠牲者、被害者", example: "Many victims received help.", exampleJa: "多くの被害者が支援を受けた。" },
  { word: "volunteer", pos: "名詞/動詞", meaning: "ボランティア(をする)", example: "She volunteers at the hospital.", exampleJa: "彼女は病院でボランティアをしている。" },
  { word: "warn", pos: "動詞", meaning: "警告する", example: "He warned us about the danger.", exampleJa: "彼は私たちに危険を警告した。" },
  { word: "waste", pos: "動詞/名詞", meaning: "無駄にする/廃棄物", example: "Don't waste your time.", exampleJa: "時間を無駄にしてはいけない。" },
  { word: "wealth", pos: "名詞", meaning: "富", example: "Health is more important than wealth.", exampleJa: "健康は富より大切だ。" },
  { word: "whether", pos: "接続詞", meaning: "〜かどうか", example: "I don't know whether he will come.", exampleJa: "彼が来るかどうか分からない。" },
  { word: "witness", pos: "名詞/動詞", meaning: "目撃者/目撃する", example: "She was a witness to the accident.", exampleJa: "彼女はその事故の目撃者だった。" },
  { word: "wonder", pos: "動詞/名詞", meaning: "不思議に思う/驚異", example: "I wonder why he is late.", exampleJa: "なぜ彼が遅いのか不思議に思う。" },
  { word: "worth", pos: "形容詞", meaning: "〜の価値がある", example: "This book is worth reading.", exampleJa: "この本は読む価値がある。" }
];
